name: Deploy Lambda

on:
  push:
    branches: [ "main" ]

jobs:
  provisioning:
    runs-on: ubuntu-latest
    outputs:
      bypass_state_bucket_name: ${{ steps.export.outputs.bypass_state_bucket_name }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configurar AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.8

      - name: Criar Backend Transformer
        run: |
          cd terraform/transformer
          cat > backend.hcl <<EOF
          bucket = "${{ secrets.STATE_BUCKET_NAME }}"
          key    = "terraform/bypass-lambda/state.tfstate"
          region = "us-east-1"
          EOF
          cat backend.hcl

      - name: Terraform Apply Transformer
        id: tf_transformer
        run: |
          cd terraform/transformer
          terraform init -backend-config=backend.hcl
          terraform apply -var="bypass_state_bucket_name=${{ secrets.STATE_BUCKET_NAME }}" -auto-approve 

      - name: Export Terraform outputs
        id: export
        run: |
          cd terraform
          echo "transformer_ec2_public_ip=$(terraform output -raw transformer_ec2_public_ip)" >> $GITHUB_OUTPUT

  setup:
    needs: provisioning
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configurar AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      - name: Criar .env
        run: |
          cd src
          echo "TRANSFORMER_EC2_PUBLIC_IP=${{ needs.provisioning.outputs.transformer_ec2_public_ip }}" > .env

  deploy:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Criar Backend Lambda
        run: |
          cd terraform/lambda
          cat > backend.hcl <<EOF
          bucket = "${{ secrets.STATE_BUCKET_NAME }}"
          key    = "terraform/bypass-lambda/state.tfstate"
          region = "us-east-1"
          EOF
          cat backend.hcl

      - name: Terraform Apply Lambda
        id: tf_lambda
        run: |
          cd terraform/lambda
          terraform init -backend-config=backend.hcl
          terraform apply -var="bypass_state_bucket_name=${{ secrets.STATE_BUCKET_NAME }}" -auto-approve 
